WIP systemd: make sure IP address is configured before network.target
setup-ip script can be called in two places:
1. from udev rule
2. from qubes-misc-post.service

The former one may fail if happen before qubes-db daemon is started. The
later one will fix it, but in the meantime some services (like whonix
update proxy sanity check) may expect to have already working network
(before are ordered after network.target or even network-online.target).

Delaying udev rules processing seems unreasonable, so introduce another
systemd service responsible for just configuring IP address. This does
not replace udev rule (but during startup will duplicate the same task),
because it is still needed to handle dynamic network switch. Also
the call in qubes-misc-post may be needed to handle DispVM startup
(network needs to be re-configured after restoring savefile).

Another idea would be to order qubes-misc-post.service after
network-online.target.

This commit is work in progres. It doesn't deal with the case where
initial setup-ip call from udev rule succeed. Second call will fail,
marking qubes-setup-ip service as failed. Also the third call (from
qubes-misc-post.service) will almost always fail - probably in every VM
but DispVM.

QubesOS/qubes-issues#2198

diff --git a/network/setup-ip b/network/setup-ip
--- a/network/setup-ip
+++ b/network/setup-ip
@@ -9,6 +9,12 @@ disabledns=`qubesdb-read /qubes-service/disable-dns-server 2> /dev/null`
 # Location of files which contains list of protected files
 PROTECTED_FILE_LIST='/etc/qubes/protected-files.d'
 
+if ! [ -e /sys/class/net/$INTERFACE ]; then
+    # silently ignore non-existing interfaces
+    # if interface will be added later, udev rule will call this script again
+    exit 0
+fi
+
 ip=`/usr/bin/qubesdb-read /qubes-ip 2> /dev/null`
 if [ x$ip != x ]; then
     netmask=`/usr/bin/qubesdb-read /qubes-netmask`
